spring:
  datasource:
    url: jdbc:mysql://studydb.c7a24emoahxy.ap-northeast-2.rds.amazonaws.com:3306/studydb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: 11111111
  jpa:
    hibernate:
      ddl-auto: none # create, create-drop, validate, update
    show-sql: true

upload:
  image:
    location: D:/git/SpringBoot-JPA-React/frontend/public/img/