server:
  servlet:
    encoding:
      charset: utf-8
      enabled: true
      
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
    
  jpa:
    hibernate:
      ddl-auto: update # create, create-drop, validate, update
    show-sql: true
    
jwt:
  cookie-name: secretkey
  secret: youcantrevealthesecretkey
  expiration-ms: 30
  refresh-expiration-ms: 180