server:
  servlet:
    encoding:
      charset: utf-8
      enabled: true

spring:
  profiles:
    active: local
    include: secret

  servlet.multipart.max-file-size: 10MB # uploaded files
  servlet.multipart.max-request-size: 10MB # multipart/form-data requests

  messages:
    basename: i18n/validation